require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/*'
    - 'script/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
    - config/initializers/*
    - config/environments/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/initializers/*

Style/Documentation:
  Enabled: false

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/views/**/*

RSpec/MessageChain:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false
