version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PG_HOST: 127.0.0.1
          PG_USER: todolist_admin
          RAILS_ENV: test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: todolist_admin
          POSTGRES_DB: todolist_api_test
caches: 
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}
commands:
  run_linters:
    description: command to start linters
    steps:
      - run: 
          name: rubocop
          command: bundle exec rubocop
      - run: 
          name: fasterer
          command: bundle exec fasterer

  run_specs:
    steps:
      - run: 
          name: run specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb")"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $TEST_FILES
          environment:
            DATABASE_URL: "postgres://todolist_admin@localhost:5432/todolist_api_test"

  defaults:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: gem install bundler:2.0.2
      - run: bundle install
      - run: yarn install
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://todolist_admin@localhost:5432/todolist_api_test"
      - save_cache:
          key: *bundle_cache
          paths:
            - bundle vendor/bundle
      
jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs
workflows:
  version: 2.0
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
