---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  api/v1/auth:
    post:
      summary: Registration
      tags:
      - Authentication
      parameters:
      - name: params
        in: doby
        schema:
          type: object
          properties:
            user[username]:
              type: string
            user[password]:
              type: string
            user[password_confirmation]:
              type: string
          required:
          - user[username]
          - user[password]
          - user[password_confirmation]
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                definitions: {}
                "$schema": http://json-schema.org/draft-07/schema#
                "$id": https://example.com/object1589968328.json
                title: Root
                type: object
                required:
                - data
                properties:
                  data:
                    "$id": "#root/data"
                    title: Data
                    type: object
                    required:
                    - type
                    - id
                    - attributes
                    - links
                    properties:
                      type:
                        "$id": "#root/data/type"
                        title: Type
                        type: string
                        default: ''
                        examples:
                        - users
                        pattern: "^.*$"
                      id:
                        "$id": "#root/data/id"
                        title: Id
                        type: string
                        default: ''
                        examples:
                        - '5'
                        pattern: "^.*$"
                      attributes:
                        "$id": "#root/data/attributes"
                        title: Attributes
                        type: object
                        required:
                        - username
                        - created-at
                        - updated-at
                        properties:
                          username:
                            "$id": "#root/data/attributes/username"
                            title: Username
                            type: string
                            default: ''
                            examples:
                            - string5
                            pattern: "^.*$"
                          created-at:
                            "$id": "#root/data/attributes/created-at"
                            title: Created-at
                            type: string
                            default: ''
                            examples:
                            - '2020-05-20T09:51:58.876Z'
                            pattern: "^.*$"
                          updated-at:
                            "$id": "#root/data/attributes/updated-at"
                            title: Updated-at
                            type: string
                            default: ''
                            examples:
                            - '2020-05-20T09:51:58.876Z'
                            pattern: "^.*$"
                      links:
                        "$id": "#root/data/links"
                        title: Links
                        type: object
                        required:
                        - self
                        properties:
                          self:
                            "$id": "#root/data/links/self"
                            title: Self
                            type: string
                            default: ''
                            examples:
                            - "/api/v1/users/5"
                            pattern: "^.*$"
            application/xml:
              schema:
                definitions: {}
                "$schema": http://json-schema.org/draft-07/schema#
                "$id": https://example.com/object1589968328.json
                title: Root
                type: object
                required:
                - data
                properties:
                  data:
                    "$id": "#root/data"
                    title: Data
                    type: object
                    required:
                    - type
                    - id
                    - attributes
                    - links
                    properties:
                      type:
                        "$id": "#root/data/type"
                        title: Type
                        type: string
                        default: ''
                        examples:
                        - users
                        pattern: "^.*$"
                      id:
                        "$id": "#root/data/id"
                        title: Id
                        type: string
                        default: ''
                        examples:
                        - '5'
                        pattern: "^.*$"
                      attributes:
                        "$id": "#root/data/attributes"
                        title: Attributes
                        type: object
                        required:
                        - username
                        - created-at
                        - updated-at
                        properties:
                          username:
                            "$id": "#root/data/attributes/username"
                            title: Username
                            type: string
                            default: ''
                            examples:
                            - string5
                            pattern: "^.*$"
                          created-at:
                            "$id": "#root/data/attributes/created-at"
                            title: Created-at
                            type: string
                            default: ''
                            examples:
                            - '2020-05-20T09:51:58.876Z'
                            pattern: "^.*$"
                          updated-at:
                            "$id": "#root/data/attributes/updated-at"
                            title: Updated-at
                            type: string
                            default: ''
                            examples:
                            - '2020-05-20T09:51:58.876Z'
                            pattern: "^.*$"
                      links:
                        "$id": "#root/data/links"
                        title: Links
                        type: object
                        required:
                        - self
                        properties:
                          self:
                            "$id": "#root/data/links/self"
                            title: Self
                            type: string
                            default: ''
                            examples:
                            - "/api/v1/users/5"
                            pattern: "^.*$"
        '422':
          description: Invalid request
          content: {}
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000/api/v1/
